# A simple action usage
name: Helios
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Android Kernel Build Action
      uses: dabao1955/kernel_build_action@v1.6.3
            
      with:
          kernel-url: https://github.com/tejas101k/kernel_xiaomi_vayu
          kernel-branch: fifteen
          depth: 1
          config: vayu_user_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
          ksu: true
          ksu-version: v0.9.5
          ccache: true
          android-version: 15
          aosp-clang-version: r522817
          disable-lto: true
          anykernel3: true
          extra-cmd: LD=ld.lld AR=llvm-ar NM=llvm-nm  STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf
          
